rubik/radon

- MANIFEST.in
When packaging the sdist, it is sometimes useful to have the
documentation available to install on the system as well.
> add docs to sdist

- .codeclimate.yml
- Dockerfile
- codeclimate-radon
- radon/cli/__init__.py
- radon/cli/harvest.py
- radon/cli/tools.py
- radon/tests/test_cli.py
- radon/tests/test_cli_tools.py
This PR creates a native Code Climate integration in Radon by
adding:
1) Dockerfile to run Radon as an engine
2) --codeclimate report format
3) `get_content` and `get_remediation_point` methods that provide informational issue content and a measure of the amount of effort needed to repair an engineering problem.
> Add support for Code Climate

- Dockerfile
- codeclimate-radon
Install Python 2.7 onto the Docker image and allow a user to specify which version of Python should be used in analysis when running via Code Climate.
* Switch base image to python:3.5.1-slim
* Shell-escape paths for os.system
* Skip analysis when provided an empty list of paths
> Add Python 2 support to Code Climate engine

- setup.py
As broken as Python packaging is, this is supposed to make radon's egg
executable when installed e.g. as a `setup_requires` or `tests_require`
dependency.
> Make radon eggsecutable

- radon/cli/tools.py
- radon/tests/test_cli_tools.py
The Code Climate Platform expects that engines emit location data with integer values only. Radon is in complete compliance with the spec with the slight exception of the error result that generates a custom issue from the error details.
This commit casts the captured line number (grabbed from the error content) to an int, before it's passed off to the issue formatter.
> Ensure that error issues have integer location values

- radon/cli/tools.py
- radon/tests/test_cli_tools.py
By default `open()` function using `locale.getpreferredencoding(False)`
encdoing (see https://docs.python.org/3/library/functions.html#open).
On not english versions Windows `locale.getpreferredencoding(False)`
return a strange encodings, like 'cp1251' on russian version.
There is no way to change `locale.getpreferredencoding(False)` to utf-8 on Windows.
This modification allow to change `cli.tools.open()` encoding by setting
it in envinronment variable RADONFILESENCODING.
For example:
```
D:\>type test.py
def a():
"not latin utf-8 char ╨Ш"
print(1)
D:\>radon cc test.py
test.py
ERROR: 'charmap' codec can't decode byte 0x98 in position 34: character
maps to <undefined>
D:\>set RADONFILESENCODING=utf-8
D:\>radon cc test.py
test.py
F 1:0 a - A
D:\>
```
> Closes rubik/radon#86

- Dockerfile
* Bumped Python 3 to 3.5.2
* Bumped Python 2 to 2.7.13
* Switched base to alpine. Now image is 4x smaller (118.3 MiB vs 482.2 MiB)
Code Climate will use current master (3ab8c78).
I tested the image in both py3 and py2 modes.
> Updated Dockerfile for Code Climate

- codeclimate-radon
Since we can't pass the `RADONFILESENCODING` when using environments like Code Climate, making it a parte of YAML configuration sounds like a way to enable this.
> Accept an `encoding` config through the Code Climate config.

- radon/raw.py
- radon/tests/test_raw.py
- test_requirements.txt
Perform the raw analysis using a single iterator.
Add test cases that cover line continuations and unusual docstrings.
> Use python tokenizer to identify single-line comments and docstrings.

- codeclimate-radon
* Updates `codeclimate-radon` to not refer to specific python3.x version
* Will effectively bump python from `3.5.2` to `3.6.1` when incorporated in Code Climate
This should address the string interpolation issue here: https://github.com/rubik/radon/issues/108
Alpine edge now uses python version`3.6.1` for the [python3 package](https://pkgs.alpinelinux.org/packages?name=python3&branch=edge&repo=&arch=&maintainer=).
Since the Dockerfile builds from [alpine:edge](https://github.com/rubik/radon/blob/master/Dockerfile#L1), just rebuilding the docker image will update python to 3.6.1:
```
(16/16) Installing python3 (3.6.1-r2)
```
However `codeclimate-radon` has an explicit reference to `python3.5`, which doesn't work after the update. I replaced it with the symlinked `python3` rather than …
> Adds support for python 3.6 in Code Climate

- docs/commandline.rst
```
$ radon cc --show_complexity some/path/whatever.py
usage: radon [-h] [-v] {cc,raw,mi} ...
radon: error: unrecognized arguments: --show_complexity
```
> fix typo in long option in docs

- codeclimate-radon
We're in the process of improving how we handle configurations, and ran into this. A defect in our old config handling code meant that many non-stringy values got coerced into strings, including numbers & bools. That was undesirable behavior, but unfortunately we were depending on it here by only comparing the user's specified `python_version` to potential string values.
This change will allow the Radon engine to work with our fixed config code that doesn't coerce these values, while remaining compatible with older versions of our CLI that will still be coercing these values.
> Code Climate wrapper: fix some config support

- radon/cli/__init__.py
- radon/cli/harvest.py
This pull request is in reference to issue #125. It adds the rudimentary command `radon hal` to print the Halstead complexity measures for a file on the command line. There are features that would be nice to have (e.g., printing the complexity measures for functions, similar to the cyclomatic complexity command), but I think that this duplicates the existing capability of `h_visit`.
@rubik, in #125 you stated that this feature would need to use the `Harvester` API. Is this what you had in mind?
> Add Halstead command (#125)

- README.rst
Codacy uses Radon by default to calculate metrics for python projects therefore, it would be cool to have it listed on the readme file. 👍 
Thanks!
> Add Codacy to the Readme file

- README.rst
CodeFactor uses Radon by default mainly for Complexity metric. It would be nice to have it on readme page.
Thanks.
> Add CodeFactor to 'On a Continuous Integration server' section on README

- docs/commandline.rst
This adds some documentation for the `hal` subcommand. Most of the docs are identical to previous commands, but the `hal`-specific flags are also discussed.
> Add docs for `hal` subcommand

- radon/__main__.py
so a "python -m radon" works as expected.
> add a __main__ module

- docs/conf.py
```
Whilst working on the Reproducible Builds effort [0], we noticed
that radon could not be built reproducibly. This is due to the
documentation including the current build date.
This was originally filed in Debian as #912152 [1].
The attached patch uses the SOURCE_DATE_EPOCH environment variable,
more info of which can be found at [2].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/912152
[2] https://reproducible-builds.org/specs/source-date-epoch/
```
> Make the build reproducible.

- docs/flake8.rst
This pull request removes an additional space and adds an empty line. The current setting causes wrong indentation, as visible here: https://radon.readthedocs.io/en/latest/flake8.html
> Fix indentation for flake8 doc

- README.rst
This commit corrects the coala organisation
default website URL in README.rst. Also,
corrects the "coala" name which starts with
small "c" instead of caps "C".
Fixes #167
> README.rst: Correct coala website URL

- radon/cli/harvest.py
> Import Py3's super() for Py2 users

- .travis.yml
- radon/visitors.py
- requirements.txt
- setup.py
- tox.ini
Fixes #183
_From the docs:_ 
Deprecated since version 3.8: Class ast.Constant is now used for all constants. Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases.
This caused numbers to be ignored for the Halstead Metrics.
All tests pass now for Python 3.8.
> Python 3.8

- radon/complexity.py
- radon/contrib/flake8.py
- radon/tests/test_complexity_utils.py
- setup.py
Due to extraction of `flake8_polyfill` into extra requirement, it's import in `radon.complexity` should be conditional. As a consequences, the whole `Flake8Checker` should be conditional, too. Because it's dependent on this import. It is much easier to move the whole thing into it's own module, rather than check for presence of `flake8_polyfill`. It is guaranteed that this module would be imported only by `flake8`, when extra requirement is installed.
Another option would be to check for presence of `flake8_polyfill` and then create the class:
```python
try:
from flake8_polyfill import options
except ImportError:
pass
else:
class Flake8Checker(object):
<...>
```
> Move `Flake8Checker` into separete module

- radon/cli/tools.py
- radon/tests/test_cli_tools.py
I encountered a small bug inspecting a library by `radon cc --md`. All the `Type` field values were identical to `C`.
How it looked like:
| Filename | Name | Type | Start:End Line | Complexity | Clasification |
| -------- | ---- | ---- | -------------- | ---------- | ------------- |
| tinydb/middlewares.py | CachingMiddleware.flush | C | 110:117 | 2 | A |
| tinydb/middlewares.py | CachingMiddleware.write | C | 101:108 | 2 | A |
| tinydb/middlewares.py | CachingMiddleware.read | C | 93:99 | 2 | A |
| tinydb/middlewares.py | CachingMiddleware | C | 73:124 | 2 | A |
| tinydb/middlewares.py | Middleware | C | 7:70 | 2 | A |
| tinydb/middlewares.py | CachingMiddleware.close | C | 119:124 | 1 | A |
| tinydb/middlewares.py | CachingMiddleware.__init__ | C | 85:91 | 1 | A |
| …
> Fix CC Mardown type field value

- .travis.yml
- CHANGELOG
- Pipfile
- radon/__init__.py
- radon/contrib/flake8.py
- radon/tests/run.py
- requirements.txt
- setup.py
- test_requirements.txt
Drops support for flake8 2.x as mentioned in https://github.com/rubik/radon/issues/217#issuecomment-846799621
- Bumps version to 5.0.0.
- Tests passing locally on Python 2.7 and 3.6.
- New `Pipfile.lock` was not generated.
> Drop support for flake8 2.x

- radon/cli/colors.py
- radon/tests/test_cli_colors.py
> GH-182: Allow forcing colored/coloured output

- requirements.txt
- setup.py
The `future` package is not used anywhere in the code, so remove
the dependency.
> chore: remove obsolete future dep

- README.rst
- docs/commandline.rst
- radon/cli/__init__.py
- setup.py
Fixes: https://github.com/rubik/radon/issues/220
This enables pyproject.toml support for radon.
Decisions I made the maintainer should be aware of before merging:
- Automatic pyproject.toml support for python 3.11+
- Optional pyproject.toml support for python <3.11 if you install with:
```sh 
pip install radon[toml]
```
- Silently ignores pyproject.toml if:
- no pyproject.toml file is found
- no toml parsing library is available
- Raises an exception if:
- toml file is found and is parsed incorrectly.
I'm happy to change anything that isn't quite in the spirit of radon.
> pyproject.toml support

- radon/cli/harvest.py
- radon/cli/tools.py
- radon/tests/test_complexity_visitor.py
- radon/visitors.py
Found via `codespell -S docs -L ue,hav,ot`
> docs: fix typos

- radon/tests/test_ipynb.py
Three tests in test_ipynb.py currently fail in Windows due to forward slashes in expected paths. This PR solves that by passing path sub-components to `os.path.join` instead.
> Fix test_ipynb.py in Windows

- pyproject.toml
The pyproject.toml is missing the tool.poetry.scripts section, which means that builds that rely only on pyproject.toml will not install it.
> Add radon CLI script to pyproject.toml

- docs/commandline.rst
I don't know if this is the norm in Python or not, but many other command line tools I used accept list by taking multiple arguments after the option, allowing specifying the option multiple times, or comma-separated list like this.
Based on my personal experience, I tried repeating the option multiple times because that's the most common usage I experienced and then immediately got into issues. That's why I want to add this clarification to the docs.
> Add clarification about multi-value exclude/ignore
